#Appium and Devices
platformName = Android
deviceName = RRCT200R3ER
automationName = UiAutomator2
appiumURL = http://127.0.0.1:4723/
appPackage = com.indomaret.klikindomaret
appActivity = .ngsCexmFBytBw
noReset = true